dev-deployment:
  variables:
    GIT_STRATEGY: fetch
  script:
    - bash ~/gitlab/NextJS/nextjs-projectdeploy-yarn-v1.sh
  environment:
    name: Development
    url: https://speakwide-ui.dedicateddevelopers.us/
  tags:
    - dev-runner
  only:
    - dev

development-deployment:
  variables:
    GIT_STRATEGY: fetch
  script:
    - bash ~/gitlab/NextJS/nextjs-projectdeploy-development-yarn-v1.sh
  environment:
    name: Development
    url: https://speakwide-fe.dedicateddevelopers.us
  tags:
    - development-runner
  only:
    - development

